---
- name: installing bash-completion package
  ansible.builtin.apt:
    name: bash-completion
- name: add text to bashrc file
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    block: |
      if [ -f /usr/share/bash-completion/bash_completion ]; then
      . /usr/share/bash-completion/bash_completion
      elif [ -f /etc/bash_completion ]; then
      . /etc/bash_completion
      fi

      source <(semaphore completion bash)
